# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b77fa93ad02d6fe928829e577ff77172e5576059d413302d618b4eea67055f1407f4bb5660bc5ec797e8385ee1475f03963da417c783848ba7b47d8886e0b198

test:
  secret_key_base: 4d2df02eedd665c691a51cf0c7881b7d69834bcda69fbeb39eaae9f61430074f033c8a0b777a09f017807b8322b94566084e8f2f93b7c83784ca6cb252cf3059

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
